import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Lato } from "next/font/google";

const lato = Lato({
  subsets: ["latin"], // you can specify other subsets as needed
  weight: ["400", "700", "900"], // specify the weights you need
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dhruvin Vaghani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
